// Copyright 2026 Ch3nyang & MrRSS Team. All rights reserved.
//
// Package config provides settings keys for database initialization
// CODE GENERATED - DO NOT EDIT MANUALLY
// To add new settings, edit internal/config/settings_schema.json and run: go run tools/settings-generator/main.go
package config

// SettingsKeys returns all valid setting keys
func SettingsKeys() []string {
	return []string{"ai_api_key", "ai_chat_enabled", "ai_chat_profile_id", "ai_custom_headers", "ai_endpoint", "ai_model", "ai_search_enabled", "ai_search_profile_id", "ai_summary_profile_id", "ai_summary_prompt", "ai_translation_profile_id", "ai_translation_prompt", "ai_usage_limit", "ai_usage_tokens", "auto_cleanup_enabled", "auto_show_all_content", "baidu_app_id", "baidu_secret_key", "close_to_tray", "content_font_family", "content_font_size", "content_line_height", "custom_css_file", "custom_translation_body_template", "custom_translation_enabled", "custom_translation_endpoint", "custom_translation_headers", "custom_translation_lang_mapping", "custom_translation_method", "custom_translation_name", "custom_translation_response_path", "custom_translation_timeout", "deepl_api_key", "deepl_endpoint", "default_view_mode", "feed_drawer_expanded", "feed_drawer_pinned", "freshrss_api_password", "freshrss_auto_sync_interval", "freshrss_enabled", "freshrss_last_sync_time", "freshrss_server_url", "freshrss_sync_on_startup", "freshrss_username", "full_text_fetch_enabled", "google_translate_endpoint", "hover_mark_as_read", "image_gallery_enabled", "language", "last_global_refresh", "last_network_test", "layout_mode", "max_article_age_days", "max_cache_size_mb", "max_concurrent_refreshes", "media_cache_enabled", "media_cache_max_age_days", "media_cache_max_size_mb", "media_proxy_fallback", "microsoft_api_key", "microsoft_endpoint", "microsoft_region", "mtran_endpoint", "mtran_token", "network_bandwidth_mbps", "network_latency_ms", "network_speed", "notion_api_key", "notion_enabled", "notion_page_id", "obsidian_enabled", "obsidian_vault", "obsidian_vault_path", "proxy_enabled", "proxy_host", "proxy_password", "proxy_port", "proxy_type", "proxy_username", "refresh_mode", "retry_timeout_seconds", "rsshub_api_key", "rsshub_enabled", "rsshub_endpoint", "rules", "shortcuts", "shortcuts_enabled", "show_article_preview_images", "show_floating_toc", "show_hidden_articles", "startup_on_boot", "summary_enabled", "summary_length", "summary_provider", "summary_trigger_mode", "target_language", "tencent_region", "tencent_secret_id", "tencent_secret_key", "theme", "translation_enabled", "translation_only_mode", "translation_provider", "update_interval", "window_height", "window_maximized", "window_width", "window_x", "window_y", "zotero_api_key", "zotero_enabled", "zotero_user_id"}
}
